import banner_02 from '../assets/images/banner-02.jpg'
import banner_07 from '../assets/images/banner-07.jpg'
import banner_08 from '../assets/images/banner-08.jpg'
import banner from '../assets/images/banner.webp'
import bg_video_1 from '../assets/images/bg-video-01.jpg.webp'
import blog_1 from '../assets/images/blog-01.jpg'
import blog_2 from '../assets/images/blog-02.jpg'
import blog_3 from '../assets/images/blog-03.jpg'
import cards1 from '../assets/images/cards1.webp'
import cards2 from '../assets/images/cards2.webp'
import cards3 from '../assets/images/cards3.webp'
import cards4 from '../assets/images/cards4.webp'
import cards5 from '../assets/images/cards5.webp'
import cards6 from '../assets/images/cards6.webp'
import carousel1 from '../assets/images/carousel1.jpg'
import carousel2 from '../assets/images/carousel2.jpg'
import carousel3 from '../assets/images/carousel3.webp'
import discover from '../assets/images/discover.png.webp'
import express from '../assets/images/express.png.webp'
import gallery_3 from '../assets/images/gallery-03.jpg'
import gallery_7 from '../assets/images/gallery-07.jpg'
import gallery_9 from '../assets/images/gallery-09.jpg'
import gallery_13 from '../assets/images/gallery-13.jpg'
import gallery_15 from '../assets/images/gallery-15.jpg'
import image from '../assets/images/image.png'
import item_2 from '../assets/images/item-02.jpg'
import item_3 from '../assets/images/item-03.jpg'
import item_5 from '../assets/images/item-05.jpg'
import item_7 from '../assets/images/item-07.jpg'
import item_card_1 from '../assets/images/item-cart-01.jpg'
import item_card_2 from '../assets/images/item-cart-02.jpg'
import item_card_3 from '../assets/images/item-cart-03.jpg'
import logo from '../assets/images/logo.png.webp'
import mastercard from '../assets/images/mastercard.png.webp'
import paypal from '../assets/images/paypal.png.webp'
import visa from '../assets/images/visa.png.webp'
import shopItem1 from '../assets/images/shopi2.webp'
import shopItem2 from '../assets/images/shopy3.webp'
import shopItem3 from '../assets/images/shopy4.webp'
import shopItem4 from '../assets/images/shopy5.webp'
import shopItem5 from '../assets/images/shopy6.webp'
import shopItem6 from '../assets/images/shopy7.webp'
import shopItem7 from '../assets/images/shopy8.webp'
import shopItem8 from '../assets/images/shop-item-09.jpg'
import shopItem9 from '../assets/images/shop9.webp'

export default {banner,banner_02,banner_07,banner_08,bg_video_1,blog_1,blog_2,
    blog_3,cards1,cards2,cards3,cards4,cards5,cards6,carousel1,carousel2,carousel3,discover,
    express,gallery_13,gallery_15,gallery_3,gallery_7,gallery_9,image,item_2,item_3,item_5,
    item_7,item_card_1,item_card_2,item_card_3,logo,mastercard,paypal,shopItem1,shopItem2,
    shopItem3,shopItem4,shopItem5,shopItem6,shopItem7,shopItem8,visa,shopItem9}